apiVersion : apps/v1
kind: Deployment
metadata:
  name: victordelangelwebgoat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victordelangelwebgoat
  template:
    metadata:
      labels:
        app: victordelangelwebgoat 
    spec:
      containers:
        - name: victordelangelwebgoat 
          image: videlaacr.azurecr.io/victordelangelwebgoat
          ports:
          - containerPort: 8080